name: gcov pass check
runs:
  using: "node12"
# main: "judge-gcov.js"
  main: "index.js"
inputs:
  log:
    description: 'gcov -b log'
    required: true
outputs:
  pass:
    description: 'pass/fail'

